### PR TITLE
Deployment handling interface

### PR DESCRIPTION
**Pull request by michaelwheeler**
Looking for feedback on this approach to addressing #26. A few items to call out...

1. When a launch occurs with a deployment ID that has not been seen previously by the tool, we are now creating a new, inactive `LtiDeployment`.
2. To account for the previous change we are handling launches with inactive deployments using the new `handle_inactive_deployment` method of `LtiLaunchBaseView`. By default a slightly helpful message is returned (better than the previous behavior of raising an exception, I think). This also allows for more sophisticated behaviors, like redirecting to a page where the user could submit a deployment activation request or associate it with a paid license.
3. A tool can modify a deployments status prior to handling a launch by implementing the new `launch_setup` method. Suggestions for a more appropriate name are welcome. This allows workflows like automatically activating all deployments for a specific registration (or for _every_ registration).

### CODE REVIEW

**Comment by cmurtaugh** [comment]
This looks like a good, flexible approach that will work well for our use case! :+1:

**Comment by doreilly** [comment]
Thanks for getting this work started Michael.

I've been trying to wrap my head around where best to handle the decision to create a `LtiDeployment`. My initial reaction is that _creating_ a resource in a `find_by_…` method, feels a bit unexpected. Upon further review, it does seem like we're limited by the control flow of `pylti1p3`, so this is a logical enough spot. If I'm reading this right, there isn't a possibility of these resources being created without reasonable assurance that it's a valid situation, given that it's happening in a validated OIDC response (with a validated `Registration` beforehand).

I appreciate the extension of the base view to have an extension point to override the response for inactive deployments on a per-project basis.

Is there ever a case where we wouldn't want to create an `LtiDeployment`? In other words, what argument would there be against making what you have drafted here the default?

Assuming the answer to that question is "Yes", we'd have to consider whether it's the right solution is to always create a record, or to make it switchable. I'm thinking of a flag on `DjangoToolConfig` that is switchable from somewhere—add a better worded option where `create_deployment_if_not_present` as an optional argument to the initializer, and then using that to trigger creation or not. That might have to be configured from a Django setting, given that the message launch fetch is also managed in middleware, making project-level customization less convenient. I'm not convinced the increase in complexity is a better choice than just creating an inactive `LtiDeployment` in every case as you have here and coping with that after the fact.

**Comment by michaelwheeler** [comment]
This is ready for a quick review when you're back @doreilly.

**Comment by michaelwheeler** [comment]
@doreilly I'll go ahead and merge this, unless you have any changes you'd like to see.

**Pull request merged**
