### PR TITLE
Move role normalization to utils

### LINKED ISSUE #6: Find a better home for role normalization
The `LtiMembership.normalize_role` method feels like it should probably be a function in `utils` or similar.

### PR DESCRIPTION
**Pull request by michaelwheeler**
Closes #6.

### CODE REVIEW

**Comment by michaelwheeler** [comment]
Had to include some slightly unpleasant changes to manage circular imports, but `normalize_role` feels more at home in `utils`.

**Comment by doreilly** [comment]
> Had to include some slightly unpleasant changes to manage circular imports, but `normalize_role` feels more at home in `utils`.

I see what you mean…

It's not my preferred way of handling things, but it's certainly possible and (not _necessarily_ bad) to make the import in `models.py` a local one. E.g.

```python
class LtiContext(models.Model):
    ...
    def update_memberships(self, member_data: List[dict]):
        from .utils import normalize_roles
        ...
```
This would avoid the circular import problem, but we'd want to be good about about unit test coverage to ensure we don't break the import later.

What are you feelings about it?

**Comment by michaelwheeler** [comment]
> What are you feelings about it?

It probably would be less disruptive, thanks for the suggestion. I'll put it together and see how it feels.

**Comment by michaelwheeler** [comment]
Closing in favor of #20.

**Pull request closed without merging**
